// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMT.Api.Data;

#nullable disable

namespace PMT.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116033428_create_initial_structure")]
    partial class create_initial_structure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMT.Core.Models.Developer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_DEVELOPER_ACTIVE");

                    b.ToTable("Developer", (string)null);
                });

            modelBuilder.Entity("PMT.Core.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActualHours")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("INT");

                    b.Property<long>("ManagerId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_PROJECT_STATUS");

                    b.HasIndex("Title")
                        .HasDatabaseName("IDX_PROJECT_TITLE");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("PMT.Core.Models.ProjectDeveloper", b =>
                {
                    b.Property<long>("ProjectId")
                        .HasColumnType("BIGINT");

                    b.Property<long>("DeveloperId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("ProjectId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("ProjectDeveloper", (string)null);
                });

            modelBuilder.Entity("PMT.Core.Models.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActualHours")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR");

                    b.Property<long?>("DeveloperId")
                        .HasColumnType("BIGINT");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("INT");

                    b.Property<long>("ProjectId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_TASK_STATUS");

                    b.HasIndex("Title")
                        .HasDatabaseName("IDX_TASK_TITLE");

                    b.ToTable("TaskItem", (string)null);
                });

            modelBuilder.Entity("PMT.Core.Models.Project", b =>
                {
                    b.HasOne("PMT.Core.Models.Developer", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PMT.Core.Models.ProjectDeveloper", b =>
                {
                    b.HasOne("PMT.Core.Models.Developer", "Developer")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMT.Core.Models.Project", "Project")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMT.Core.Models.TaskItem", b =>
                {
                    b.HasOne("PMT.Core.Models.Developer", "Developer")
                        .WithMany("Tasks")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PMT.Core.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMT.Core.Models.Developer", b =>
                {
                    b.Navigation("ManagedProjects");

                    b.Navigation("ProjectDevelopers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PMT.Core.Models.Project", b =>
                {
                    b.Navigation("ProjectDevelopers");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
